---
- name: file check
  hosts: all
  tasks:
   - name: file checking
     stat:
      path: file3
     register: a
   - name: Print output
     debug:
      var: a
   - name: create file
     file:
       name: file3
       state: touch
     when: a.stat.exists == false


