---
- name: Setup of Jenkins
  hosts: all
  tasks:
   - name: Install required s/w's for Jenkins
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no}
      - {a: maven,b: no}
   - name: Download jenkins.war
     get_url:
      url: https://get.jenkins.io/war-stable/2.277.4/jenkins.war
      dest: /tmp
- name: Setup tomcat9 and required s/w on qa and prodservers
  hosts: all
  tasks:
   - name: Install required s/w for tomcat
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: tomcat9,b: yes}
      - {a: tomcat9-admin,b: no}
   - name: Copy tomcat users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
     notify: Restart tomcat
  handlers:
   - name: Restart tomcat
     service:
      name: tomcat9
      state: restarted
...




